version: '3'

services:
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: be
    restart: always
    ports:
      - "80:80"
    tty: true
    volumes:
      - "C:/Users/Katushenka/PycharmProjects/busy_fit_api/backend/app:/code/app:rw"
